### ISSUE TITLE
sdist upload to PyPI fails

### ISSUE THREAD

**Issue by boegel** [hpcugent/vsc-install#16]
I ran into this while trying to upload vsc-install 0.9.12 to PyPI:

```
$ python setup.py sdist upload
INFO: This is (based on) vsc.install.shared_setup 0.9.12
INFO: run_tests from base dir /Users/kehoste/work/vsc-install (using executable /Users/kehoste/work/vsc-install/setup.py)
WARN: cleanup lib/vsc_install.egg-info
INFO: generated list: ['vsc.install', 'vsc']
INFO: generated packages list: ['vsc.install', 'vsc']
INFO: makesetupcfg set to True, (re)creating setup.cfg
INFO: found license /Users/kehoste/work/vsc-install/LICENSE with md5sum 5f30f0716dfdd0d91eb439ebec522ec2
INFO: Found license name LGPLv2+ and classifier License :: OSI Approved :: GNU Lesser General Public License v2 or later (LGPLv2+)
INFO: setting license LGPLv2+
INFO: No name defined, trying to determine it
INFO: found match url git@github.com:hpcugent/vsc-install in /Users/kehoste/work/vsc-install/.git/config
INFO: found match name vsc-install in /Users/kehoste/work/vsc-install/.git/config
INFO: Removing None download_url
INFO: get_name_url returns {'url': 'https://github.com/hpcugent/vsc-install', 'name': 'vsc-install'}
INFO: using long_description vsc-install provides shared setuptools functions and classes for python libraries developed by UGent's HPC group
INFO: generated list: []
INFO: generated scripts list: []
INFO: running sdist
INFO: running egg_info
INFO: creating lib/vsc_install.egg-info
INFO: writing requirements to lib/vsc_install.egg-info/requires.txt
INFO: writing lib/vsc_install.egg-info/PKG-INFO
INFO: writing top-level names to lib/vsc_install.egg-info/top_level.txt
INFO: writing dependency_links to lib/vsc_install.egg-info/dependency_links.txt
INFO: writing manifest file 'lib/vsc_install.egg-info/SOURCES.txt'
INFO: reading manifest file 'lib/vsc_install.egg-info/SOURCES.txt'
INFO: writing manifest file 'lib/vsc_install.egg-info/SOURCES.txt'
INFO: looking for extra dist files
WARN: warning: vsc_sdist: standard file not found: should have one of README, README.rst, README.txt

INFO: running check
INFO: sdist make_release_tree original base_dir vsc-install-0.9.12 files ['setup.cfg', 'setup.py', 'lib/vsc/__init__.py', 'lib/vsc/fancylogger.py', 'lib/vsc/install/__init__.py', 'lib/vsc/install/headers.py', 'lib/vsc/install/shared_setup.py', 'lib/vsc/install/testing.py', 'lib/vsc_install.egg-info/PKG-INFO', 'lib/vsc_install.egg-info/SOURCES.txt', 'lib/vsc_install.egg-info/dependency_links.txt', 'lib/vsc_install.egg-info/requires.txt', 'lib/vsc_install.egg-info/top_level.txt', 'setup.py', 'lib/vsc_install.egg-info/SOURCES.txt']
INFO: sdist from shared_setup setup.py current dir /Users/kehoste/work/vsc-install
INFO: creating vsc-install-0.9.12
INFO: creating vsc-install-0.9.12/lib
INFO: creating vsc-install-0.9.12/lib/vsc
INFO: creating vsc-install-0.9.12/lib/vsc/install
INFO: creating vsc-install-0.9.12/lib/vsc_install.egg-info
INFO: making hard links in vsc-install-0.9.12...
INFO: hard linking setup.cfg -> vsc-install-0.9.12
INFO: hard linking setup.py -> vsc-install-0.9.12
INFO: hard linking lib/vsc/__init__.py -> vsc-install-0.9.12/lib/vsc
INFO: hard linking lib/vsc/fancylogger.py -> vsc-install-0.9.12/lib/vsc
INFO: hard linking lib/vsc/install/__init__.py -> vsc-install-0.9.12/lib/vsc/install
INFO: hard linking lib/vsc/install/headers.py -> vsc-install-0.9.12/lib/vsc/install
INFO: hard linking lib/vsc/install/shared_setup.py -> vsc-install-0.9.12/lib/vsc/install
INFO: hard linking lib/vsc/install/testing.py -> vsc-install-0.9.12/lib/vsc/install
INFO: hard linking lib/vsc_install.egg-info/PKG-INFO -> vsc-install-0.9.12/lib/vsc_install.egg-info
INFO: hard linking lib/vsc_install.egg-info/SOURCES.txt -> vsc-install-0.9.12/lib/vsc_install.egg-info
INFO: hard linking lib/vsc_install.egg-info/dependency_links.txt -> vsc-install-0.9.12/lib/vsc_install.egg-info
INFO: hard linking lib/vsc_install.egg-info/requires.txt -> vsc-install-0.9.12/lib/vsc_install.egg-info
INFO: hard linking lib/vsc_install.egg-info/top_level.txt -> vsc-install-0.9.12/lib/vsc_install.egg-info
INFO: copying setup.cfg -> vsc-install-0.9.12
INFO: Writing vsc-install-0.9.12/setup.cfg
INFO: recopying dest vsc-install-0.9.12/setup.py if hardlinked
INFO: copying /Users/kehoste/work/vsc-install/setup.py -> vsc-install-0.9.12
INFO: running shared_setup as main, not adding it to sdist
INFO: copying /Users/kehoste/work/vsc-install/LICENSE -> vsc-install-0.9.12
INFO: copying /Users/kehoste/work/vsc-install/README.md -> vsc-install-0.9.12
INFO: Creating tar archive
INFO: removing 'vsc-install-0.9.12' (and everything under it)
INFO: running upload
Traceback (most recent call last):
  File "setup.py", line 1288, in <module>
    action_target(PACKAGE)
  File "setup.py", line 1272, in action_target
    setupfn(**x)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 971, in run_command
    cmd_obj.ensure_finalized()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/upload.py", line 61, in finalize_options
    self.repository = config.get('server-login', 'repository')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'server-login'
```

This seems to be related to `$HOME/.pypirc`, here's mine (with passwords censored):

```
[distutils]
index-servers =
    pypi
    testpypi

[pypi]
username:boegel
password:<password>

[testpypi]
username:boegel
password:<password>
```

This has worked fine before, not sure what changed (my `$HOME/.pypirc` was not touched since this last worked)...

@stdweird: can you check if you can reproduce this?

**Comment by boegel** [comment]
I'm seeing this both on my laptop and on the HPC-UGent login nodes...

**Comment by boegel** [comment]
relevant (but doesn't help in terms of pinpointing the problem, it seems): https://bitbucket.org/tarek/distribute/issues/346/upload-fails-without-server-login-but

**Comment by stdweird** [comment]
work as expected on both `pypi` and `testpypi`, but you changed ownership to hpcugent, right?

**Comment by stdweird** [comment]
hmm, doesn't appear on pypi page

**Comment by stdweird** [comment]
ah no, patience is a virtue it seems....https://pypi.python.org/pypi/vsc-install/0.9.12

**Comment by boegel** [comment]
I didn't *change* ownership, I also gave `hpcugent` right to push to PyPI, but yeah, may be related, thanks for the reminder...

**Comment by boegel** [comment]
@stdweird: I'm running into the same issues now with vsc-base when using the `hpcugent` credentials...

Can you specify what you run exactly, and what's in your `.pypirc` (if anything)?

**Comment by stdweird** [comment]
i have a very recent setuptools in my environment, and i see that's not specified in the `requires`
```
[stdweird@localhost vsc-install (master)]$ python -c 'import distutils;print distutils.__file__;import setuptools;print setuptools.__file__'
/usr/lib64/python2.7/distutils/__init__.pyc
/home/stdweird/.local/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/__init__.pyc
```

**Comment by boegel** [comment]
Mine is definitely older, but I don't see how it can be broken all of a sudden, it was working fine since ever... :-/

So, something in `vsc-install` is somehow not compatible with older setuptools versions?

```
$ python -c 'import distutils;print distutils.__file__;import setuptools;print setuptools.__file__; print setuptools.version.__version__' 
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/__init__.pyc
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/__init__.pyc
1.1.6
```

**Comment by stdweird** [comment]
well, then we should bump the requires to something more recent or fix the incompatibility.

**Comment by boegel** [comment]
I'd rather do the latter, but then we need to figure out what's incompatible exactly... I'll try and figure that out.

**Comment by boegel** [comment]
uploading does work with `setuptools` v2.0, so I suggest we specify that as minimal required version (released Dec'13): https://github.com/hpcugent/vsc-install/pull/31

**Comment by boegel** [comment]
no longer relevant, closing...
